package pongproject;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JPanel;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ethanmiller
 *
 */
public class PongFrame extends javax.swing.JFrame {

    public void launchBall() {
        int ballx = fieldWidth / 2;
        int bally = fieldHeight / 2;
        int ballxv = randoms.nextInt(16) + 5;
        int other = randoms.nextInt(2);
        if (other % 2 == 0) {
            ballxv = ballxv;
        } else {
            ballxv = -ballxv;
        }
        int ballyv = randoms.nextInt(31) - 15;
        balls.add(new Ball(ballx, bally, ballxv, ballyv, 5, Color.red));
    }

    public PongFrame() {
        initComponents();

        clock.start();
    }

    public int leftScore = 0;
    public int rightScore = 0;
    public int leftPaddley;    // These are the y coordinates of the center of the left paddle
    public int rightPaddley;  // These should be between 0 and 300
    public int mousex;
    public int mousey;// These are updated to reflect current mouse
    public int tickcount;
    public static final int ballRadius = 5;
    public static final int paddleWidth = 5;
    public static final int paddleHeight = 50;
    public static final int fieldWidth = 600;
    public static final int fieldHeight = 300;
    public static final int leftPaddlex = 15;
    public static final int rightPaddlex = fieldWidth - 15;
    public Random randoms = new Random();
    public ArrayList<Ball> balls = new ArrayList<Ball>();
    public Paddle left = new Paddle(leftPaddlex, paddleHeight, paddleWidth, 5);
    public Paddle right = new Paddle(rightPaddlex, paddleHeight, paddleWidth, 10);

    public Timer clock = new Timer(50, new ActionListener() {  // 50ms delay between ticks

        public void actionPerformed(ActionEvent e) {
            tick();               // Write a method named tick to advance your game
            ViewPanel.repaint();

        }

        public void tick() {

            tickcount++;
            if (tickcount % 20 == 0) {
                launchBall();
            }
            for (Ball b : balls) {
                b.move();
                right.Bounce(b);
                left.Bounce(b);
            }

            ArrayList<Ball> nb = new ArrayList<Ball>();
            for (Ball b : balls) {
                if (!b.score) {
                    nb.add(b);
                }
            }
            balls = nb;

            right.sety(mousey);

            int min = 800;
            int t = 300;
            for (Ball b : balls) {
                if (b.xv < 0 && b.x < min) {
                    min = b.x;
                    t = b.y;
                }
            }
            left.sety(t);

            RightScore.setText("Right Score: " + left.score);
            LeftScore.setText("Left Score: " + right.score);

        }
    });

    public class MyPanel extends JPanel {

        @Override
        public void paint(Graphics g) {
            super.paint(g);
            left.paint(g);
            right.paint(g);
            for (Ball b : balls) {

                b.paint(g);

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewPanel = new MyPanel();
        LeftScore = new javax.swing.JLabel();
        RightScore = new javax.swing.JLabel();
        JLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ViewPanel.setBackground(new java.awt.Color(0, 0, 0));
        ViewPanel.setPreferredSize(new java.awt.Dimension(600, 300));
        ViewPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ViewPanelMouseMoved(evt);
            }
        });

        LeftScore.setForeground(new java.awt.Color(255, 0, 51));
        LeftScore.setText("Left Score:");

        RightScore.setForeground(new java.awt.Color(255, 0, 0));
        RightScore.setText("Right Score:");

        JLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JLabel1.setForeground(new java.awt.Color(255, 0, 0));
        JLabel1.setText("Pong By Ethan");

        javax.swing.GroupLayout ViewPanelLayout = new javax.swing.GroupLayout(ViewPanel);
        ViewPanel.setLayout(ViewPanelLayout);
        ViewPanelLayout.setHorizontalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LeftScore)
                .addGap(160, 160, 160)
                .addComponent(JLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(RightScore)
                .addGap(30, 30, 30))
        );
        ViewPanelLayout.setVerticalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel1)
                    .addGroup(ViewPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LeftScore)
                            .addComponent(RightScore))))
                .addContainerGap(270, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ViewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPanelMouseMoved
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_ViewPanelMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PongFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel LeftScore;
    private javax.swing.JLabel RightScore;
    private javax.swing.JPanel ViewPanel;
    // End of variables declaration//GEN-END:variables
}
